<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\viewer.ico</ApplicationIcon>
    <Version>1.0.8</Version>
    <AssemblyVersion>1.0.8.0</AssemblyVersion>
    <FileVersion>1.0.8.0</FileVersion>
    <InformationalVersion>1.08</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Translations\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <Target Name="BuildUpdater" BeforeTargets="Build;Publish">
    <MSBuild Projects="..\Updater\Updater.csproj" Targets="Build" Properties="Configuration=$(Configuration)" />
  </Target>

  <Target Name="CopyUpdaterToOutput" AfterTargets="Build">
    <ItemGroup>
      <UpdaterOutput Include="..\Updater\bin\$(Configuration)\net8.0-windows\Updater.*" />
    </ItemGroup>
    <Copy SourceFiles="@(UpdaterOutput)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CopyUpdaterToPublish" AfterTargets="Publish">
    <ItemGroup>
      <UpdaterOutput Include="..\Updater\bin\$(Configuration)\net8.0-windows\Updater.*" />
    </ItemGroup>
    <Copy SourceFiles="@(UpdaterOutput)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
